### ISSUE TITLE
DOCS: Improve details on how to test out Sandbox from creating a User to Receiving a webhook notifications

### ISSUE THREAD

**Issue by arun-singh** [Teal-Connect/docs#11]
Also add an extra point for a connection and payslip upload and describe what's the difference

Remove default user details from sandbox create user section

**Comment by andre-teal** [comment]
Also, good to add a button/link to connect to the Postman collection with some context on it

**Comment by olavandeira** [comment]
We can't create a public collection until we upgrade postman. Once we set up the public collection we can see if we add one button to the entire collection or if Postman has a goto button for each specific request, so we can can have a button per step

**Comment by andre-teal** [comment]
**Wrong word - Supply (missing an L)**: An API key for authentication: please ask your Teal connection to supp**l**y you with an API key

**Comment by andre-teal** [comment]
Now that we have a webapp, we should also mention that and add any necessary guidance

**Comment by olavandeira** [comment]
@andre-teal  Now that we are hosting a public collection it is recommended to have a consistent branding across tools

Could you please share the following? 



![Image](https://github.com/Teal-Connect/docs/assets/104200235/7fc9791c-dc30-4485-ba1d-eb8cd146cd52)

**Comment by olavandeira** [comment]
> [@olavandeira](https://github.com/olavandeira) I believe the Postman collection block should be fixed, if it still remains let me know please

@andre-teal  do you mean the issue of the button taking the whole screen?

**Comment by olavandeira** [comment]
> Now that we have a webapp, we should also mention that and add any necessary guidance

@andre-teal Created a separate task for this https://github.com/orgs/Teal-Connect/projects/1/views/1?pane=issue&itemId=61311797
