### ISSUE TITLE
DOCS: Review Execution Methods (Quickstart)

### ISSUE THREAD

**Issue by arun-singh** [Teal-Connect/docs#14]
See if we need to add more context on how to use them

**Comment by olavandeira** [comment]
@andre-teal  who is going to be the consumer of this information? did we have any concern back in the past?

For developers is good enough. As a dev I would personally not pay a lot of attention to this particular part of the documentation


FYI  @luchesar @arun-singh

**Comment by olavandeira** [comment]
Discussion on slack after this comment: https://gotealgo.slack.com/archives/C061MKVDWH5/p1713455930207329

No clear action, let's discuss on Monday sprint planning

**Comment by andre-teal** [comment]
@olavandeira just saw the question here, but believe I answered on slack already - the consumer of this information (Quickstart specifically) will be either dev or product teams
